- id: '1583167744310'
  alias: Front Door Opened
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: not
    conditions:
    - condition: template
      value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  - condition: state
    entity_id: var.disable_notifications
    state: 'False'
  action:
  - service: notify.pushover
    data:
      message: The front Door at 34 Deer Track has opened without parents home.
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 1800
        expire: 3600
- id: '1583167835627'
  alias: Garage Door Entry Opened
  description: ''
  trigger:
  - entity_id: binary_sensor.garage_entry
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: not
    conditions:
    - condition: template
      value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  - condition: state
    entity_id: var.disable_notifications
    state: 'False'
  action:
  - service: notify.pushover
    data:
      message: 34DT Garage Entry Opened without parents home.
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 1800
        expire: 3600
- id: '1583283013697'
  alias: Piano Room Motion Detected
  description: ''
  trigger:
  - entity_id: binary_sensor.piano_room_motion_home_security_motion_detection
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: not
    conditions:
    - condition: template
      value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  - condition: state
    entity_id: var.disable_notifications
    state: 'False'
  action:
  - service: notify.pushover
    data:
      message: Piano Room Motion Detected without parents home.
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 1800
        expire: 3600
- id: '1583283118831'
  alias: Exercise Room Motion Detected
  description: ''
  trigger:
  - entity_id: binary_sensor.exercise_room_motion_home_security_motion_detection
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: not
    conditions:
    - condition: template
      value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  - condition: state
    entity_id: var.disable_notifications
    state: 'False'
  action:
  - service: notify.pushover
    data:
      message: Exercise Room Motion Detected without parents home.
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 1800
        expire: 3600
- id: '1583838999172'
  alias: Kitchen Motion Detected
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_motion_home_security_motion_detection
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: not
    conditions:
    - condition: template
      value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  - condition: state
    entity_id: var.disable_notifications
    state: 'False'
  action:
  - service: notify.pushover
    data:
      message: Kitchen Area Motion Detected without parents home.
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 1800
        expire: 3600
- id: '1583840584254'
  alias: Joe Left Home
  description: ''
  trigger:
  - entity_id: person.joe
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Joe Left Home
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: -2
- id: '1583840738068'
  alias: Jamie Left Home
  description: ''
  trigger:
  - entity_id: person.jamie
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Jamie Left Home
      target:
      - six50joePhone
      data:
        priority: 0
- id: '1583840787571'
  alias: Joe Arrived Home
  description: ''
  trigger:
  - entity_id: person.joe
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Joe Arrived Home
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: -2
- id: '1583840831037'
  alias: Jamie Arrived Home
  description: ''
  trigger:
  - entity_id: person.jamie
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Jamie Arrived Home
      target:
      - six50joePhone
      data:
        priority: 0
- id: '1583884186260'
  alias: Kitchen Sliding Door Openend
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_sliding_doors_status
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: not
    conditions:
    - condition: template
      value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  - condition: state
    entity_id: var.disable_notifications
    state: 'False'
  action:
  - service: notify.pushover
    data:
      message: Kitchen Sliding Door Opened while parents not home.
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 1800
        expire: 3600
- id: '1583970826722'
  alias: Family Room Sliding Doors Opened
  description: ''
  trigger:
  - entity_id: binary_sensor.family_room_sliding_door_status
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: not
    conditions:
    - condition: template
      value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  - condition: state
    entity_id: var.disable_notifications
    state: 'False'
  action:
  - service: notify.pushover
    data:
      message: Family Room sliding door opened while parents not home.
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 1800
        expire: 3600
- id: '1585016862253'
  alias: Check Lakehouse Disconnected
  description: ''
  trigger:
  - entity_id: sensor.lakehouse_hassio
    from: Up
    platform: state
    to: Down
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Lakehouse had been reachable but is now not
      target:
      - six50joePhone
  mode: single
- id: '1585017089811'
  alias: Check Lakehouse Connected
  description: ''
  trigger:
  - entity_id: sensor.lakehouse_hassio
    from: Down
    platform: state
    to: Up
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Lakehouse had not been reachable, but is now
      target:
      - six50joePhone
  mode: single
- id: '1585054962692'
  alias: Store Kitchen Motion Time
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_motion_home_security_motion_detection
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload_template: '{{ as_timestamp(now()) | timestamp_custom(''%m-%d-%y %H:%M:%S'')
        }}'
      topic: hass/storage/motion/on_time/kitchenmotion
    service: mqtt.publish
- id: '1594236029982'
  alias: Reset Air Conditioning Warning
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.air_cond_warn_triggered
    service: input_boolean.turn_off
- id: Living Room Lights On
  alias: Living Room Lights On
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 51
      property_key: '001'
  condition: []
  action:
  - service: input_select.select_next
    entity_id: input_select.living_room_scene
  - service: hue.hue_activate_scene
    data_template:
      group_name: Living room
      scene_name: '{{ states.input_select.living_room_scene.state }}'
  mode: single
- id: Living Room Lights Off
  alias: Living Room Lights Off
  trigger:
  - event_data:
      node_id: 51
      property_key: '002'
    event_type: zwave_js_value_notification
    platform: event
  condition: []
  action:
  - service: homeassistant.turn_off
    entity_id: light.hue_color_lamp_1
  - service: homeassistant.turn_off
    entity_id: light.hue_color_downlight_1
  - service: homeassistant.turn_off
    entity_id: light.hue_color_downlight_2
  - service: input_select.select_option
    data:
      entity_id: input_select.living_room_scene
      option: Dance Party
  mode: single
- id: '1605561802870'
  alias: Daily Device Batteries Check
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - event: scan_device_batteries
    event_data:
      state: 'on'
  mode: single
- id: '1607037712815'
  alias: Path Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: d5c9618bf075d4657def9c581c7aa9eb
    entity_id: switch.front_path_lights
    domain: switch
  mode: single
- id: '1607037786126'
  alias: Path Lights Off
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: d5c9618bf075d4657def9c581c7aa9eb
    entity_id: switch.front_path_lights
    domain: switch
  mode: single
- id: 34dt_low_temperature
  alias: 34DT Low Temperature
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.thermostat_piano_room_temperature
    below: '55'
  condition: []
  action:
  - service: notify.pushover
    data:
      message: 34 Deer Track temperature dangerously low!
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 900
        expire: 7200
        sound: climb
  mode: single
- id: set_joe_home_state
  alias: Set Joe Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: joe
      state: home
  mode: single
- id: set_joe_not_home_state
  alias: Set Joe Not Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: joe
      state: not_home
- id: set_jamie_home_state
  alias: Set Jamie Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: jamie
      state: home
- id: set_jamie_not_home_state
  alias: Set Jamie Not Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: jamie
      state: not_home
- id: '1614001081756'
  alias: Set Joe Home State 2
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: joe
      state: home
  mode: single
- id: notify_jamie_zone_change
  alias: Notify when jamie enters or leaves a zone
  description: ''
  trigger:
    platform: state
    entity_id: person.jamie
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
  - service: notify.pushover
    data_template:
      data:
        title: Jamie Location update {{ states.sensor.time.state }}
        priority: -1
      message: '{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state
        == ''not_home'' %}has left {{ trigger.from_state.state }}{% endif %}{% if
        trigger.from_state.state == ''not_home'' %}arrived at {{ trigger.to_state.state
        }}{% endif %}'
      target:
      - six50joePhone
- id: notify_joe_zone_change
  alias: Notify when joe enters or leaves a zone
  description: ''
  trigger:
    platform: state
    entity_id: person.joe
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
  - service: notify.pushover
    data_template:
      data:
        title: Joe Location update {{ states.sensor.time.state }}
        priority: -1
      message: '{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state
        == ''not_home'' %}has left {{ trigger.from_state.state }}{% endif %}{% if
        trigger.from_state.state == ''not_home'' %}arrived at {{ trigger.to_state.state
        }}{% endif %}'
      target:
      - six50joePhone
- id: water_flowing
  alias: Water Flowing While Away
  description: ''
  trigger:
  - platform: state
    entity_id: var.water_usage_rate
  condition:
  - condition: not
    conditions:
    - condition: template
      value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  - condition: state
    entity_id: var.disable_notifications
    state: 'False'
  action:
  - service: notify.pushover
    data:
      message: Water flowing while away
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 1800
        expire: 3600
  mode: single
- id: set_trusted_home
  alias: Set Trusted Home
  description: ''
  trigger:
  - platform: state
    entity_id: person.joe
  - platform: state
    entity_id: person.jamie
  - platform: time
    at: 07:00:00
  condition:
  - condition: or
    conditions:
    - condition: template
      value_template: '{{ states(''person.joe'').lower()  == ''home'' or states(''person.jamie'').lower()
        == ''home'' }}'
    - condition: time
      after: 07:00:00
      before: 09:00:00
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: var.set
    data:
      entity_id:
      - var.trusted_home
      value: true
  mode: single
- id: set_not_trusted_home
  alias: Set Not Trusted Home
  description: ''
  trigger:
  - platform: state
    entity_id: person.joe
  - platform: state
    entity_id: person.jamie
  - platform: time
    at: 09:00:00
  condition:
  - condition: not
    conditions:
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states(''person.joe'').lower()  == ''home'' or states(''person.jamie'').lower()
          == ''home'' }}'
      - condition: time
        after: 07:00:00
        before: 09:00:00
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
  - service: var.set
    data:
      entity_id:
      - var.trusted_home
      value: false
  mode: single
- id: trust_home_test
  alias: Testing
  description: ''
  trigger:
  - platform: state
    entity_id: var.trusted_home
  condition:
  - condition: template
    value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  action:
  - service: var.set
    data:
      entity_id:
      - var.test_var
      value: TRUSTED HOME TRIGGERED
- id: trust_not_home_test
  alias: Testing
  description: ''
  trigger:
  - platform: state
    entity_id: var.trusted_home
  condition:
  - condition: template
    value_template: '{{ states(''var.trusted_home'').lower()  != ''true'' }}'
  action:
  - service: var.set
    data:
      entity_id:
      - var.test_var
      value: TRUSTED *NOT* HOME TRIGGERED
- id: '1671150769271'
  alias: Jemma's Xmas Lights On
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  condition:
  - condition: time
    before: '23:00:00'
    after: 01:00:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - type: turn_on
    device_id: b68f96ed392414310918db90bc500a8d
    entity_id: switch.christmas_light_cube_plug
    domain: switch
  mode: single
- id: '1671150852845'
  alias: Jemma's Xmas Lights Off
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: b68f96ed392414310918db90bc500a8d
    entity_id: switch.christmas_light_cube_plug
    domain: switch
  mode: single
- id: '1671155957111'
  alias: Turn Christmas Tree Lights ON
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition:
  - condition: time
    before: '22:00:00'
    weekday:
    - mon
    - sun
    - tue
    - wed
    - thu
    - fri
    - sat
    after: 01:00:00
  action:
  - type: turn_on
    device_id: fc4880b1bdb62d78e29098762238f05f
    entity_id: 054ab60f7960515d6cf4f6847542e4eb
    domain: switch
  mode: single
- id: '1671156651114'
  alias: Turn off Christmas Tree Lights
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: fc4880b1bdb62d78e29098762238f05f
    entity_id: 054ab60f7960515d6cf4f6847542e4eb
    domain: switch
  mode: single
- id: '1700344410607'
  alias: Ping Wave Device Test
  description: ''
  trigger: []
  condition: []
  action:
  - device_id: 93ffc0d5c56d124c808cbb60db7e6fc9
    domain: zwave_js
    entity_id: 6e8302ce6d3209adcec921d5d7ef27d9
    type: refresh_value
    refresh_all_values: true
  mode: single
- id: '1700346127425'
  alias: Test Wave Device Updated
  description: ''
  trigger:
  - platform: device
    device_id: 93ffc0d5c56d124c808cbb60db7e6fc9
    domain: button
    entity_id: 6e8302ce6d3209adcec921d5d7ef27d9
    type: pressed
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Test ZWave updated
  mode: single
- id: enable_all_notifications
  alias: enable_all_notifications
  description: Disable all HA notifications
  trigger: []
  condition: []
  action:
  - service: var.set
    data:
      entity_id: var.disable_notifications
      value: false
  mode: single
- id: '1704406845222'
  alias: New automation
  description: stop_notifications
  trigger: []
  condition: []
  action:
  - service: var.set
    metadata: {}
    data:
      entity_id: var.disable_notifications
      value: true
  mode: single
- id: '1704406913838'
  alias: resume_notifications
  description: ''
  trigger: []
  condition: []
  action:
  - service: var.set
    metadata: {}
    data:
      entity_id: var.disable_notifications
      value: false
  mode: single
- id: '1704407021473'
  alias: stop_notifications
  description: ''
  trigger: []
  condition: []
  action:
  - service: var.set
    metadata: {}
    data:
      entity_id: var.disable_notifications
      value: true
  mode: single
- id: '1704412552860'
  alias: send_notification
  description: Send a home alert
  trigger: []
  condition:
  - condition: not
    conditions:
    - condition: template
      value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  - condition: state
    entity_id: var.disable_notifications
    state: 'False'
  action:
  - service: notify.pushover
    data:
      message: '{{ states(''var.notification_message'') }}'
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 1800
        expire: 3600
      title: 34DT Home Alert
  mode: single
