- id: '1583840584254'
  alias: Joe Left Home
  description: ''
  trigger:
  - entity_id: person.joe
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Joe Left Home
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: -2
- id: '1583840738068'
  alias: Jamie Left Home
  description: ''
  trigger:
  - entity_id: person.jamie
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Jamie Left Home
      target:
      - six50joePhone
      data:
        priority: 0
- id: '1583840787571'
  alias: Joe Arrived Home
  description: ''
  trigger:
  - entity_id: person.joe
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Joe Arrived Home
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: -2
- id: '1583840831037'
  alias: Jamie Arrived Home
  description: ''
  trigger:
  - entity_id: person.jamie
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Jamie Arrived Home
      target:
      - six50joePhone
      data:
        priority: 0
- id: '1605561802870'
  alias: Daily Device Batteries Check
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - event: scan_device_batteries
    event_data:
      state: 'on'
  mode: single
- id: '1607037712815'
  alias: Path Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: d5c9618bf075d4657def9c581c7aa9eb
    entity_id: switch.front_path_lights
    domain: switch
  mode: single
- id: '1607037786126'
  alias: Path Lights Off
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: d5c9618bf075d4657def9c581c7aa9eb
    entity_id: switch.front_path_lights
    domain: switch
  mode: single
- id: set_joe_home_state
  alias: Set Joe Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: joe
      state: home
  mode: single
- id: set_joe_not_home_state
  alias: Set Joe Not Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: joe
      state: not_home
- id: set_jamie_home_state
  alias: Set Jamie Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: jamie
      state: home
- id: set_jamie_not_home_state
  alias: Set Jamie Not Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: jamie
      state: not_home
- id: '1614001081756'
  alias: Set Joe Home State 2
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: joe
      state: home
  mode: single
- id: notify_jamie_zone_change
  alias: Notify when jamie enters or leaves a zone
  description: ''
  trigger:
    platform: state
    entity_id: person.jamie
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
  - service: notify.pushover
    data_template:
      data:
        title: Jamie Location update {{ states.sensor.time.state }}
        priority: -1
      message: '{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state
        == ''not_home'' %}has left {{ trigger.from_state.state }}{% endif %}{% if
        trigger.from_state.state == ''not_home'' %}arrived at {{ trigger.to_state.state
        }}{% endif %}'
      target:
      - six50joePhone
- id: notify_joe_zone_change
  alias: Notify when joe enters or leaves a zone
  description: ''
  trigger:
    platform: state
    entity_id: person.joe
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
  - service: notify.pushover
    data_template:
      data:
        title: Joe Location update {{ states.sensor.time.state }}
        priority: -1
      message: '{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state
        == ''not_home'' %}has left {{ trigger.from_state.state }}{% endif %}{% if
        trigger.from_state.state == ''not_home'' %}arrived at {{ trigger.to_state.state
        }}{% endif %}'
      target:
      - six50joePhone
- id: '1671150769271'
  alias: Jemma's Xmas Lights On
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  condition:
  - condition: time
    before: '23:00:00'
    after: 01:00:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - type: turn_on
    device_id: b68f96ed392414310918db90bc500a8d
    entity_id: switch.christmas_light_cube_plug
    domain: switch
  mode: single
- id: '1671150852845'
  alias: Jemma's Xmas Lights Off
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: b68f96ed392414310918db90bc500a8d
    entity_id: switch.christmas_light_cube_plug
    domain: switch
  mode: single
- id: '1671155957111'
  alias: Turn Christmas Tree Lights ON
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition:
  - condition: time
    before: '22:00:00'
    weekday:
    - mon
    - sun
    - tue
    - wed
    - thu
    - fri
    - sat
    after: 01:00:00
  action:
  - type: turn_on
    device_id: fc4880b1bdb62d78e29098762238f05f
    entity_id: 054ab60f7960515d6cf4f6847542e4eb
    domain: switch
  mode: single
- id: '1671156651114'
  alias: Turn off Christmas Tree Lights
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: fc4880b1bdb62d78e29098762238f05f
    entity_id: 054ab60f7960515d6cf4f6847542e4eb
    domain: switch
  mode: single
- id: '1704412552860'
  alias: send_notification
  description: Send a home alert
  trigger: []
  condition:
  - condition: not
    conditions:
    - condition: template
      value_template: '{{ states(''var.trusted_home'').lower()  == ''true'' }}'
  - condition: state
    entity_id: var.disable_notifications
    state: 'False'
  action:
  - service: notify.pushover
    data:
      message: '{{ states(''var.notification_message'') }}'
      target:
      - six50joePhone
      - JamieIPhone
      data:
        priority: 2
        retry: 1800
        expire: 3600
      title: 34DT Home Alert
  mode: single
