# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include binary_sensor.yaml
template: !include template.yaml 
var: !include_dir_merge_named variables/

frontend:
  themes: !include frontend.yaml

homeassistant:
  customize: !include customize.yaml

#
# TCP sensors
#
command_line:
  - sensor:
      name: Netgear Router Admin
      command: /usr/bin/nc -z -w7 192.168.0.1 80 && echo Up || echo Down
command_line:
  - sensor:
      name: Netgear Spectrum Analyzer
      command: /usr/bin/nc -z -w7 192.168.0.1 8080 && echo Up || echo Down
command_line:
  - sensor:
      name: Lakehouse Hassio
      command: /usr/bin/nc -z -w7 12ridgegarden.dyndns.org 8123 && echo Up || echo Down

shopping_list:

logger:
  default: info
  logs:
    # log level for HA core
    homeassistant.core: fatal

    # log level for remote rpio override
    # custom_components.remote_rpi_gpio: info

    pyatv: error
    custom_components.apple_tv: error
       
owntracks:
  max_gps_accuracy: 200
  waypoints: false
  mqtt_topic: "owntracks/#"
  events_only: false
#  waypoint_whitelist:
#    - six50joe
#  region_mapping:
#    cabin: home
#    office: work

input_boolean:
  air_cond_warn_triggered:
    name: Set to true if air cond warning made
   
amcrest:
  - host: 192.168.0.54
    username: six50joe
    password: unbelief-ramp-best
    name: Living Room

  - host: 192.168.0.58
    username: six50joe
    password: unbelief-ramp-best
    name: Driveway

  - host: 192.168.0.56
    username: six50joe
    password: unbelief-ramp-best
    name: Piano Room

  - host: 192.168.0.60
    username: six50joe
    password: unbelief-ramp-best
    name: Exercise Room

camera:
  - platform: amcrest
  
sonos:
  media_player:
    hosts:
      192.168.0.18

tts:
  - platform: google_translate
    
ios:
  actions:
    - name: Living Room Mute
      background_color: "#000000"
      label:
        text: "Living Room Mute"
        color: "#808080"
      icon:
        icon: volume-variant-off
        color: "#ffffff"
    - name: Living Room Volume Mid
      background_color: "#000000"
      label:
        text: "Living Room Volume Mid"
        color: "#ffa700"
      icon:
        icon: volume-medium
        color: "#ffffff"
    - name: Living Room Volume Low
      background_color: "#000000"
      label:
        text: "Living Room Volume Low"
        color: "#fff400"
      icon:
        icon: volume-low
        color: "#ffffff"
    - name: Living Room Volume High
      background_color: "#000000"
      label:
        text: "Living Room Volume High"
        color: "#ff0000"
      icon:
        icon: volume-high
        color: "#ffffff"

switch:
  - platform: broadlink
    mac: '24:DF:A7:36:69:93'
    switches:
      - name: TV
        command_on: JgBYAAABIJQVEBEUEjcUERMSERMTEhITEjgROBEUETgTNxE4EjcUNhQRERQTERM3FBERExUQEhMSNxI4ETgTEhI4ETgROBI4EwAFHgABJkoSAAxRAAElShIADQUAAAAAAAAAAAAAAAAAAA==
        command_off: JgBYAAABIJQVEBEUEjcUERMSERMTEhITEjgROBEUETgTNxE4EjcUNhQRERQTERM3FBERExUQEhMSNxI4ETgTEhI4ETgROBI4EwAFHgABJkoSAAxRAAElShIADQUAAAAAAAAAAAAAAAAAAA==

light:
  - platform: template
    lights:
      path_lights:
        friendly_name: "Path Lights"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.front_path_lights
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.front_path_lights
      driveway_flood_light:
        friendly_name: "Driveway Flood Light"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.driveway_floodlight_sensor
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.driveway_floodlight_sensor

input_select:
  living_room_scene:
    name: Living Room Scene
    options:
      - Read
      - Night show
      - Relax
      - Energize
      - Concentrate
      - Bright
      - Nightlight
      - Spring blossom
      - Tropical twilight
      - Arctic aurora
      - Savanna sunset
      - Game Night
      - Dance Party
    initial: Read
    icon: mdi:lightbulb-multiple