# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_merge_named ha_homes_common/config

#
# Logging Levels
#
logger:
  default: info
  logs:
    # log level for HA core
    homeassistant.core: info

    # log level for remote rpio override
    # custom_components.remote_rpi_gpio: info

    pyatv: error
    custom_components.apple_tv: error

#
# Other home
#
command_line:
  - sensor:
      name: Lakehouse Hassio
      command: /usr/bin/nc -z -w7 12ridgegarden.dyndns.org 8123 && echo Up || echo Down

frontend:
  themes: !include frontend.yaml

# All HA Variables
var: !include_dir_merge_named 34dt_local/variables/

# Automations I create in the UI
automation ui: !include automations.yaml

# 34DT handmade automations
automation manual: !include_dir_merge_list 34dt_local/automations/

# Where we all are
# Traccar yaml cfg deprecated
composite: !include 34dt_local/device_trackers.yaml

# Sensors- Monitoring entities
sensor: !include_dir_merge_list 34dt_local/sensors

# TV Switch and other manually created ones
switch: !include 34dt_local/switches.yaml

# Window and Door Open / Close sensors
binary_sensor: !include 34dt_local/binary_sensor.yaml

# House lighting 
light: !include 34dt_local/lights.yaml

# House cameras
amcrest: !include 34dt_local/cameras.yaml

# Living room wall switch lighting presets
input_select: !include 34dt_local/input_select.yaml

#
# Essentially a boolean variable- used to indictate a notification was
# already made so that it doesn't repeat every time temp changes outside
# the threshold
#
input_boolean:
  air_cond_warn_triggered:
    name: Set to true if air cond warning made

sonos:
  media_player:
    hosts: 192.168.0.18

# TV / Sonos controls
ios: !include 34dt_local/ios.yaml

shopping_list:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influx_password
  max_retries: 3
  default_measurement: state