# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include binary_sensor.yaml

frontend:
  themes: !include frontend.yaml

apple_tv:

hue:
  bridges:
    - host: 192.168.0.35

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.0.70
      - 192.168.0.71
  - platform: icloud3
    username: !secret fmf_icloud
    password: !secret fmf_icloud_pw
    track_devices:
      - six50joe_iphone > six50joe@icloud.com, JoeBadge2.jpg
      - jamies_iphonex > jamiedylana@gmail.com, JamieBadge.jpg

#  - platform: icloud3
#    username: six50joe@mac.com
#    password: !secret joe_icloud
#    tracking_method: famshr
#    group: family
#    track_devices:
#      - jamies_iphonex > jamiedylana@gmail.com, JamieBadge.jpg

  
homeassistant:
  customize: !include customize.yaml

shopping_list:

# Notifications
notify:
  - name: 34DT Hassio
    platform: pushover
    api_key:  aiqsstb3fdzjfiufhry3sxp8i7tw4f
    user_key: utevcgmbad4mq263sto1k6sfw5bq45

logger:
  default: info
  logs:
    # log level for HA core
    homeassistant.core: fatal

    # log level for remote rpio override
    custom_components.remote_rpi_gpio: info

    pyatv: debug
    custom_components.apple_tv: debug
       
input_boolean:
  air_cond_warn_triggered:
    name: Set to true if air cond warning made
    
variable:
  water_usage_rate:
    value: 0
    name: WaterUsageRate
  water_usage:
    value: 0
    name: WaterUsage
  prev_water_usage:
    value: 0
    name: PrevWaterUsage
  prev_water_time:
    value: 0
    name: PrevWaterTime

amcrest:
  - host: 192.168.0.54
    username: six50joe
    password: unbelief-ramp-best
    name: Living Room

  - host: 192.168.0.58
    username: six50joe
    password: unbelief-ramp-best
    name: Driveway

  - host: 192.168.0.56
    username: six50joe
    password: unbelief-ramp-best
    name: Piano Room

  - host: 192.168.0.60
    username: six50joe
    password: unbelief-ramp-best
    name: Exercise Room

camera:
  - platform: amcrest
  
sonos:
  media_player:
    hosts:
      192.168.0.12
    
media_player:
  platform: sonos

light:
  - platform: template
    lights:
      path_lights:
        friendly_name: "Path Lights"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.path_lights_switch_switch
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.path_lights_switch_switch

input_select:
  living_room_scene:
    name: Living Room Scene
    options:
      - Read
      - Night show
      - Relax
      - Energize
      - Concentrate
      - Bright
      - Nightlight
      - Spring blossom
      - Tropical twilight
      - Arctic aurora
      - Savanna sunset
      - Game Night
      - Dance Party
    initial: Read
    icon: mdi:lightbulb-multiple