# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include binary_sensor.yaml

frontend:
  themes: !include frontend.yaml

apple_tv:

hue:
  bridges:
    - host: 192.168.0.35
  
homeassistant:
  customize: !include customize.yaml

shopping_list:

# Notifications
notify:
  - name: 34dt_hassio_joe
    platform: pushover
    api_key:  aiqsstb3fdzjfiufhry3sxp8i7tw4f
    user_key: utevcgmbad4mq263sto1k6sfw5bq45
  - name: 34dt_hassio_jamie
    platform: pushover
    api_key:  aae9b85uhv9qmzjgjfa4tzaxxjzo1h
    user_key: u9dikpjkyenayozh68ni42x8qbrv39
  - name: all
    platform: group
    services:
      - service: 34dt_hassio_joe
      - service: 34dt_hassio_jamie

logger:
  default: info
  logs:
    # log level for HA core
    homeassistant.core: fatal

    # log level for remote rpio override
    custom_components.remote_rpi_gpio: info

    pyatv: debug
    custom_components.apple_tv: debug
       
owntracks:
  max_gps_accuracy: 200
  waypoints: false
  mqtt_topic: "owntracks/#"
  events_only: false
  waypoint_whitelist:
    - six50joe
#  region_mapping:
#    cabin: home
#    office: work

input_boolean:
  air_cond_warn_triggered:
    name: Set to true if air cond warning made
   
variable:
  test_variable:
    value: initialized
    name: Testing Variable
  trusted_home:
    value: xyz
    name: Trusted Home State
  water_usage_rate:
    value: 0
    name: WaterUsageRate
  water_usage:
    value: 0
    name: WaterUsage
  prev_water_usage:
    value: 0
    name: PrevWaterUsage
  prev_water_time:
    value: 0
    name: PrevWaterTime

amcrest:
  - host: 192.168.0.54
    username: six50joe
    password: unbelief-ramp-best
    name: Living Room

  - host: 192.168.0.58
    username: six50joe
    password: unbelief-ramp-best
    name: Driveway

  - host: 192.168.0.56
    username: six50joe
    password: unbelief-ramp-best
    name: Piano Room

  - host: 192.168.0.60
    username: six50joe
    password: unbelief-ramp-best
    name: Exercise Room

camera:
  - platform: amcrest
  
sonos:
  media_player:
    hosts:
      192.168.0.18

tts:
  - platform: google_translate
    
ios:
  actions:
    - name: Living Room Mute
      background_color: "#000000"
      label:
        text: "Living Room Mute"
        color: "#808080"
      icon:
        icon: volume-variant-off
        color: "#ffffff"
    - name: Living Room Volume Mid
      background_color: "#000000"
      label:
        text: "Living Room Volume Mid"
        color: "#ffa700"
      icon:
        icon: volume-medium
        color: "#ffffff"
    - name: Living Room Volume Low
      background_color: "#000000"
      label:
        text: "Living Room Volume Low"
        color: "#fff400"
      icon:
        icon: volume-low
        color: "#ffffff"
    - name: Living Room Volume High
      background_color: "#000000"
      label:
        text: "Living Room Volume High"
        color: "#ff0000"
      icon:
        icon: volume-high
        color: "#ffffff"

switch:
  - platform: broadlink
    mac: '24:DF:A7:36:69:93'
    switches:
      - name: TV
        command_on: JgBYAAABIJQVEBEUEjcUERMSERMTEhITEjgROBEUETgTNxE4EjcUNhQRERQTERM3FBERExUQEhMSNxI4ETgTEhI4ETgROBI4EwAFHgABJkoSAAxRAAElShIADQUAAAAAAAAAAAAAAAAAAA==
        command_off: JgBYAAABIJQVEBEUEjcUERMSERMTEhITEjgROBEUETgTNxE4EjcUNhQRERQTERM3FBERExUQEhMSNxI4ETgTEhI4ETgROBI4EwAFHgABJkoSAAxRAAElShIADQUAAAAAAAAAAAAAAAAAAA==

light:
  - platform: template
    lights:
      path_lights:
        friendly_name: "Path Lights"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.front_path_lights
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.front_path_lights
      driveway_flood_light:
        friendly_name: "Driveway Flood Light"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.driveway_floodlight_sensor_current_value
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.driveway_floodlight_sensor_current_value

input_select:
  living_room_scene:
    name: Living Room Scene
    options:
      - Read
      - Night show
      - Relax
      - Energize
      - Concentrate
      - Bright
      - Nightlight
      - Spring blossom
      - Tropical twilight
      - Arctic aurora
      - Savanna sunset
      - Game Night
      - Dance Party
    initial: Read
    icon: mdi:lightbulb-multiple