#
# TCP sensors
#
- platform: command_line
  name: Netgear Router Admin
  command: /usr/bin/nc -z -w7 192.168.0.1 80 && echo Up || echo Down
- platform: command_line
  name: Netgear Spectrum Analyzer
  command: /usr/bin/nc -z -w7 192.168.0.1 8080 && echo Up || echo Down
- platform: command_line
  name: Lakehouse Hassio
  command: /usr/bin/nc -z -w7 12ridgegarden.dyndns.org 8123 && echo Up || echo Down

#
# Motion sensors
#
- platform: mqtt
  name: "Kitchen Motion Detected"
  state_topic: "hass/storage/motion/on_time/kitchenmotion"
- platform: mqtt
  name: "Piano Room Motion Detected"
  state_topic: "hass/storage/motion/on_time/pianoroommotion"
- platform: mqtt
  name: "Exercise Room Motion Detected"
  state_topic: "hass/storage/motion/on_time/exerciseroommotion"
- platform: mqtt
  name: "Driveway Motion Updated"
  state_topic: "hass/storage/motion/on_time/drivewaymotion"
- platform: template
  sensors:
    #
    # Smoke and Carbon Monixide Detectors
    #
    smoke_upstairs_status:
      friendly_name: "Smoke Upstairs Status"
      value_template: >-
        {% if is_state("sensor.smoke_detector_upstairs_alarm_level", "255") and is_state("sensor.smoke_detector_upstairs_alarm_type", "1")%}
          smoke
        {% elif is_state("sensor.smoke_detector_upstairs_alarm_level", "255") and is_state("sensor.smoke_detector_upstairs_alarm_type", "2")%}
          co
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("sensor.smoke_detector_upstairs_alarm_level", "255") and is_state("sensor.smoke_detector_upstairs_alarm_type", "1")%}
          mdi:fire
        {% elif is_state("sensor.smoke_detector_upstairs_alarm_level", "255") and is_state("sensor.smoke_detector_upstairs_alarm_type", "2")%}
          mdi:cloud-outline
        {% else %}
          mdi:smoke-detector
        {% endif %}

    smoke_main_level_status:
      friendly_name: "Smoke Main Level Status"
      value_template: >-
        {% if is_state("sensor.smoke_detector_main_level_alarm_level", "255") and is_state("sensor.smoke_detector_main_level_alarm_type", "1")%}
          smoke
        {% elif is_state("sensor.smoke_detector_main_level_alarm_level", "255") and is_state("sensor.smoke_detector_main_level_alarm_type", "2")%}
          co
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("sensor.smoke_detector_main_level_alarm_level", "255") and is_state("sensor.smoke_detector_main_level_alarm_type", "1")%}
          mdi:fire
        {% elif is_state("sensor.smoke_detector_main_level_alarm_level", "255") and is_state("sensor.smoke_detector_main_level_alarm_type", "2")%}
          mdi:cloud-outline
        {% else %}
          mdi:smoke-detector
        {% endif %}

    smoke_downstairs_status:
      friendly_name: "Smoke Downstairs Status"
      value_template: >-
        {% if is_state("sensor.smoke_detector_downstairs_alarm_level", "255") and is_state("sensor.smoke_detector_downstairs_alarm_type", "1")%}
          smoke
        {% elif is_state("sensor.smoke_detector_downstairs_alarm_level", "255") and is_state("sensor.smoke_detector_downstairs_alarm_type", "2")%}
          co
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("sensor.smoke_detector_downstairs_alarm_level", "255") and is_state("sensor.smoke_detector_downstairs_alarm_type", "1")%}
          mdi:fire
        {% elif is_state("sensor.smoke_detector_downstairs_alarm_level", "255") and is_state("sensor.smoke_detector_downstairs_alarm_type", "2")%}
          mdi:cloud-outline
        {% else %}
          mdi:smoke-detector
        {% endif %}

    driveway_motion_detected:
      friendly_name: "Driveway Motion Status"
      value_template: >-
        {% if not is_state("sensor.driveway_floodlight_sensor_burglar", "0")%}
          motion
        {% else %}
          sleep
        {% endif %}
      icon_template: >-
        {% if not is_state("sensor.driveway_floodlight_sensor_burglar", "0")%}
          mdi:motion-sensor
        {% else %}
          mdi:sleep
        {% endif %}

    inner_garage_status:
      friendly_name: "Inner Garage Sensor"
      value_template: >-
        {% if is_state("sensor.inner_garage_sensor_access_control", "22")%}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >-
        {% if is_state("sensor.inner_garage_sensor_access_control", "22")%}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}

    outer_garage_status:
      friendly_name: "Outer Garage Sensor"
      value_template: >-
        {% if is_state("sensor.outer_garage_sensor_access_control", "22")%}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >-
        {% if is_state("sensor.outer_garage_sensor_access_control", "22")%}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}

    water_gpm:
      friendly_name: "Water Usage Gallons Per Minute"
      unit_of_measurement: 'gpm'
      value_template: "{{ states('variable.water_usage_rate') }}"

    water_shutoff:
      friendly_name: "Water Main Shutoff"
      value_template: >-
        {% if is_state("switch.water_shutoff_switch", "off")%}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >-
        {% if is_state("switch.water_shutoff_switch", "off")%}
          mdi:valve-open
        {% else %}
          mdi:valve-closed
        {% endif %}
        

