- platform: template
  sensors:
    #
    # Smoke and Carbon Monixide Detectors
    #

    # Upstairs
    smoke_upstairs_status:
      friendly_name: "Smoke Upstairs Status"
      value_template: >-
        {% if is_state("binary_sensor.smoke_upstairs_smoke_detected", "on") %}
          smoke
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.smoke_upstairs_smoke_detected", "on") %}
          mdi:fire
        {% else %}
          mdi:smoke-detector
        {% endif %}

    co_upstairs_status:
      friendly_name: "Carbon Monoxide Upstairs Status"
      value_template: >-
        {% if is_state("binary_sensor.smoke_upstairs_carbon_monoxide_detected", "on") %}
          co
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.smoke_upstairs_carbon_monoxide_detected", "on") %}
          mdi:smoke
        {% else %}
          mdi:smoke-detector
        {% endif %}

    # Main Level
    smoke_main_level_status:
      friendly_name: "Smoke Main Level Status"
      value_template: >-
        {% if is_state("binary_sensor.smoke_main_level_smoke_detected", "on") %}
          smoke
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.smoke_main_level_smoke_detected", "on") %}
          mdi:fire
        {% else %}
          mdi:smoke-detector
        {% endif %}

    co_main_level_status:
      friendly_name: "Carbon Monoxide Main Level Status"
      value_template: >-
        {% if is_state("binary_sensor.smoke_main_level_carbon_monoxide_detected", "on") %}
          co
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.smoke_main_level_carbon_monoxide_detected", "on") %}
          mdi:smoke
        {% else %}
          mdi:smoke-detector
        {% endif %}

    # Downstairs
    smoke_downstairs_status:
      friendly_name: "Smoke Downstairs Status"
      value_template: >-
        {% if is_state("binary_sensor.smoke_downstairs_smoke_detected", "on") %}
          smoke
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.smoke_downstairs_smoke_detected", "on") %}
          mdi:fire
        {% else %}
          mdi:smoke-detector
        {% endif %}

    co_downstairs_status:
      friendly_name: "Carbon Monoxide Downstairs Status"
      value_template: >-
        {% if is_state("binary_sensor.smoke_downstairs_carbon_monoxide_detected", "on") %}
          co
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.smoke_downstairs_carbon_monoxide_detected", "on") %}
          mdi:smoke
        {% else %}
          mdi:smoke-detector
        {% endif %}

    driveway_motion_detected:
      friendly_name: "Driveway Motion Status"
      value_template: >-
        {% if not is_state("binary_sensor.driveway_floodlight_sensor_motion_detection", "on")%}
          motion
        {% else %}
          sleep
        {% endif %}
      icon_template: >-
        {% if not is_state("binary_sensor.driveway_floodlight_sensor_motion_detection", "on")%}
          mdi:motion-sensor
        {% else %}
          mdi:sleep
        {% endif %}

    inner_garage_status:
      friendly_name: "Inner Garage Sensor"
      value_template: >-
        {% if is_state("binary_sensor.inner_garage_access_control_window_door_is_open", "on")%}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.inner_garage_access_control_window_door_is_open", "on")%}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}

    outer_garage_status:
      friendly_name: "Outer Garage Sensor"
      value_template: >-
        {% if is_state("binary_sensor.outer_garage_access_control_window_door_is_open", "on")%}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.outer_garage_access_control_window_door_is_open", "on")%}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}

    water_gpm:
      friendly_name: "Water Usage Gallons Per Minute"
      unit_of_measurement: 'gpm'
#      value_template: "{{ states('var.water_usage_rate') }}"
      value_template: "999999"

    water_shutoff:
      friendly_name: "Water Main Shutoff"
      value_template: >-
        {% if is_state("switch.water_shutoff_switch", "off")%}
          open
        {% else %}
          closed
        {% endif %}
      icon_template: >-
        {% if is_state("switch.water_shutoff_switch", "off")%}
          mdi:valve-open
        {% else %}
          mdi:valve-closed
        {% endif %}
